name: Step 3

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: read
  actions: write
  issues: write

env:
  STEP_3_FILE: ".github/steps/4-step.md"

jobs:
  check_keywords:
    name: Check issue comment text for required keyword
    runs-on: ubuntu-latest

    outputs:
      result: ${{ steps.combine_checks.outputs.result }}

    steps:
      - name: Check for professortocat reference
        id: check_professortocat
        uses: skills/action-keyphrase-checker@v1
        continue-on-error: true
        with:
          text: ${{ github.event.comment.body }}
          keyphrase: "professortocat"
          case-sensitive: false
          minimum-occurrences: 1

      - name: Check for alert reference
        id: check_alert
        uses: skills/action-keyphrase-checker@v1
        continue-on-error: true
        with:
          text: ${{ github.event.comment.body }}
          keyphrase: "alert"
          case-sensitive: false
          minimum-occurrences: 1

      - name: Set continue output if both checks succeeded
        id: combine_checks
        run: |
          if [[ "${{ steps.check_professortocat.outcome }}" == "success" && "${{ steps.check_alert.outcome }}" == "success" ]]; then
            echo "result=success" >> "$GITHUB_OUTPUT"
          else
            echo "result=fail" >> "$GITHUB_OUTPUT"
          fi

  find_exercise:
    needs: [check_keywords]
    name: Find Exercise Issue
    if: needs.check_keywords.outputs.result == 'success'
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.6.0

  post_next_step_content:
    name: Post next step content
    needs: [find_exercise]
    runs-on: ubuntu-latest
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.6.0

      - name: Build message - step finished
        id: build-message-step-finish
        uses: skills/action-text-variables@v2
        with:
          template-file: exercise-toolkit/markdown-templates/step-feedback/step-finished-prepare-next-step.md
          template-vars: |
            next_step_number: 4

      - name: Update comment - step finished
        run: |
          gh issue comment "$ISSUE_URL" \
            --body "$ISSUE_BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_BODY: ${{ steps.build-message-step-finish.outputs.updated-text }}

      - name: Create comment - add step content
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file "$STEP_3_FILE"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create comment - watching for progress
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Disable current workflow and enable next one
        run: |
          gh workflow disable "Step 3"
          gh workflow enable "Step 4"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
